spring.application.name=engdados

# ===================================================================
# 1. PERSISTÊNCIA RELACIONAL - POSTGRESQL (Localhost)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/costa
spring.datasource.username=costa
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# 2. PERSISTÊNCIA NOSQL - MONGODB (Localhost)
# ===================================================================
# Conecta direto ao Mongo local sem precisar de autenticação complexa por enquanto
spring.data.mongodb.uri=mongodb://localhost:27017/engdados_db