# GERAL
spring.application.name=engdados

# HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PERSISTENCIA RELACIONAL
spring.datasource.url=jdbc:postgresql://localhost:5432/engdados
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# PERSISTENCIA NOSQL
spring.data.mongodb.uri=mongodb://localhost:27017/engdados

# OUTROS
spring.data.web.pageable.page-serialization-mode=via-dto
spring.data.web.pageable.max-page-size=200

# SEGURANCA (CORS)
app.security.cors.allowed-origins=*